name: Run Happy Flow Scenario

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  run-happy-flow:
    runs-on: self-hosted

    env:
      DOTNET_ROOT: ${{ github.workspace }}/.dotnet
      PATH: ${{ github.workspace }}/.dotnet:$PATH

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        run: |
          curl -sSL https://dot.net/v1/dotnet-install.ps1 -o dotnet-install.ps1
          powershell -ExecutionPolicy Bypass -File ./dotnet-install.ps1 -Version 6.0.416 -InstallDir "$env:GITHUB_WORKSPACE\.dotnet"

      - name: Restore dependencies
        run: .\.dotnet\dotnet.exe restore

      - name: Build solution
        run: .\.dotnet\dotnet.exe build --no-restore --configuration Release

      - name: Run HappyFlow.feature
        run: .\.dotnet\dotnet.exe test --no-build --filter "TestCategory=happyFlow"

