name: Run Desktop Automation

on:
  push:
    branches: master

jobs:
  desktop-test:
    runs-on: [self-hosted, windows]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Build
        run: dotnet build

      - name: Start WinAppDriver
        run: |
          Start-Process "C:\Program Files (x86)\Windows Application Driver\WinAppDriver.exe"

      - name: Run Tests
        run: dotnet test
